#!/usr/bin/env bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

#python -m cortexpy view ./DAL19_core.totRNA-18_S32_L004.pac-bio-seqs.joined.ctx \
#  --record AGGTGCTTGTTCTCTTACCCGAGATCTGATCTACATAAGACTGTAACTGTCTTGGAGTGCATCAGGGAGAGGACGAGAATGGTGAGGGGAAAAACCCAGATGAAGAGGATCGAGAACTCGACCAGCAGGCAGGTTACGTTTTCTAAGCGCAGGAACGGTCTGCTGAAGAAAGCTTACGAGCTGTCGGTGCTCTGCGATGCTGAAGTGGCACTTATTGTTTTCGCCCCCCGAGGGAAGCTCTATGAATTCGCCAATCCCAGTATGCAAAAAATGTTGGAGAGGTATCAAAAGTATTCACAAGAAAGTGACATAGATAACACTACCAAAGAGCAAGACTATCAGCATTTAAAACGAGAAATTGCAAATATGGAAGAGAGAATTAGGATCCTCGAATCAACACAAAGAAAGATGATGGGGGAAGATCTAGCATCATGTTCAGTGAAAGAATTAAATCAGCTAGAAAGCCAAGTTGAACGAGGGTTGAACCACATACGAGCACGAAAGACTAAAGTATTGGTGGATGAAATAGAACAACTTAAAAGGAAGGGGCAGGGAACTGCAGCATCATTGTGTTGGAAATGACATCCAAACATCTAACATGCACATGACCAGGTGCCGCAACTAGAAATGTACATGCATAAGGATGCATATGTAGTCAATTATACCTGGTATATGGAGAGAATCCAATACGTTTCAAAGGCATACCCAACCTGTACCTTAATGTATATTGTTCTTGCTATGATAATAAACTAATCTTCCTAAATATTTTGTACTTTTCTCTCCATAATCTCAACAATTGATAAAATATTCAAACGAAAAAAAAAAAAACCTATAGTGAGTCGTATTAATTCTGTGCTCGC \
#  --output-type json | python -m json.tool > ../public/graph.json

#python -m cortexpy view traversal ../scratch/DAL19_core.i0_ICE_samplee6591f-c18066-1-496.infer.and.totRNA-18_S32_L004.ctx \
#  AGGTGCTTGTTCTCTTACCCGAGATCTGATCTACATAAGACTGTAACTGTCTTGGAGTGCATCAGGGAGAGGACGAGAATGGTGAGGGGAAAAACCCAGATGAAGAGGATCGAGAACTCGACCAGCAGGCAGGTTACGTTTTCTAAGCGCAGGAACGGTCTGCTGAAGAAAGCTTACGAGCTGTCGGTGCTCTGCGATGCTGAAGTGGCACTTATTGTTTTCGCCCCCCGAGGGAAGCTCTATGAATTCGCCAATCCCAGTATGCAAAAAATGTTGGAGAGGTATCAAAAGTATTCACAAGAAAGTGACATAGATAACACTACCAAAGAGCAAGACTATCAGCATTTAAAACGAGAAATTGCAAATATGGAAGAGAGAATTAGGATCCTCGAATCAACACAAAGAAAGATGATGGGGGAAGATCTAGCATCATGTTCAGTGAAAGAATTAAATCAGCTAGAAAGCCAAGTTGAACGAGGGTTGAACCACATACGAGCACGAAAGACTAAAGTATTGGTGGATGAAATAGAACAACTTAAAAGGAAGGGGCAGGGAACTGCAGCATCATTGTGTTGGAAATGACATCCAAACATCTAACATGCACATGACCAGGTGCCGCAACTAGAAATGTACATGCATAAGGATGCATATGTAGTCAATTATACCTGGTATATGGAGAGAATCCAATACGTTTCAAAGGCATACCCAACCTGTACCTTAATGTATATTGTTCTTGCTATGATAATAAACTAATCTTCCTAAATATTTTGTACTTTTCTCTCCATAATCTCAACAATTGATAAAATATTCAAACGAAAAAAAAAAAAACCTATAGTGAGTCGTATTAATTCTGTGCTCGC \
#  --color 0 --max-nodes 10
#
#python -m cortexpy view traversal ./DAL19_core.i0_ICE_samplee6591f-c18066-1-496.infer.and.totRNA-18_S32_L004.ctx \
#  GTTACGTTTTCTAAGCGCAGGAACGGTCTGCTGAAGAAAGCTTACGA \
#  --color 0 --max-nodes 1000 > ../public/DAL19_core.i0_ICE_samplee6591f-c18066-1-496.infer.and.totRNA-18_S32_L004.1knodes.json

# start of dal19 core sequence
#python -m cortexpy view traversal ./DAL19_core.totRNA-18_S32_L004.pac-bio-seqs.joined.dal19.joined.ctx \
#  TATGCAAAAAATGTTGGAGAGGTATCAAAAGTATTCACAAGAAAGTG \
#  --color 0 --max-nodes 1000 > ../public/graphs/DAL19_core.totRNA-18_S32_L004.pac-bio-seqs.joined.dal19.joined.1knodes.json

#python -m cortexpy view traversal ./DAL19_core.totRNA-18_S32_L004.pac-bio-seqs.joined.dal19.joined.ctx \
#  TATGCAAAAAATGTTGGAGAGGTATCAAAAGTATTCACAAGAAAGTG \
#  --color 0 --max-nodes 10000 > ../public/graphs/DAL19_core.totRNA-18_S32_L004.pac-bio-seqs.joined.dal19.joined.10knodes.json

python -m cortexpy view traversal ./DAL19_core.totRNA-18_S32_L004.pac-bio-seqs.joined.dal19.joined.ctx \
  TATGCAAAAAATGTTGGAGAGGTATCAAAAGTATTCACAAGAAAGTG \
  --output-type contigs --output-format fasta \
  --color 0 --max-nodes 10000 > ../public/graphs/DAL19_core.totRNA-18_S32_L004.pac-bio-seqs.joined.dal19.joined.10knodes.contigs.fasta

rsync -av 'milou2:/proj/b2015052/nobackup/pacbio/pac_bio_mapped_reads_to_cortex_graphs/DAL19_core/DAL19_core.totRNA-18_S32_L004.pac-bio-seqs.joined.dal19.joined.ctx.dal19_core.traversal_2k*' ../public/graphs/

python -m http.server


